// all courses must be stored as an array of JSON objects to be passed to the VUE app
const lessons = [
    {
      id: 101,
      title: "Introduction to Algebra",
      subject: "Maths",
      location: "Class",
      price: 100,
      avaliability: 5,
      icon: "bi bi-calculator-fill",
    },
    {
      id: 102,
      title: "Learning to Paint",
      subject: "Art",
      location: "In-Person",
      price: 85,
      avaliability: 5,
      icon: "bi bi-brush",
    },
    {
      id: 103,
      title: "Concept of Drawing",
      subject: "Art",
      location: "In-Person",
      price: 40,
      avaliability: 5,
      icon: "bi bi-pencil",
    },
    {
      id: 104,
      title: 'Translation to English Language',
      subject: "English",
      location: "Class",
      price: 245,
      avaliability: 5,
      icon: "bi bi-translate",
    },
    {
      id: 105,
      title: "We Were Liars",
      subject: "English",
      location: "Book",
      price: 130,
      avaliability: 5,
      icon: "bi bi-book",
    },
    {
      id: 106,
      title: "The Blue Book of Chess",
      subject: "English",
      location: "Book",
      price: 120,
      avaliability: 5,
      icon: "bi bi-book-fill",
    },
    {
      id: 107,
      title: "Further Mathematics",
      subject: "Maths",
      location: "Class",
      price: 25,
      avaliability: 5,
      icon: "fa fa-plus",
    },
    {
      id: 108,
      title: "History of Leonardo da Vinci",
      subject: "Art",
      location: "Online",
      price: 255,
      avaliability: 5,
      icon: "bi bi-info",
    },
    {
      id: 109,
      title: "Databases and SQL",
      subject: "CST3145",
      location: "DKP",
      price: 130,
      avaliability: 5,
      icon: "bi bi-filetype-sql",
    },
    {
      id: 110,
      title: "Introduction to Java",
      subject: "CST3145",
      location: "DKP",
      price: 320,
      avaliability: 5,
      icon: "bi bi-filetype-java",
    },
    {
      id: 111,
      title: "Swimming Lessons",
      subject: "Sport",
      location: "In-Person",
      price: 500,
      avaliability: 5,
      icon: "bi bi-water",
    },
    {
      id: 112,
      title: "Introduction to Frontend Frameworks",
      subject: "CST3145",
      location: "DKP",
      price: 90,
      avaliability: 5,
      icon: "bi bi-filetype-html",
    },
  ];
  
  // module.exports = lessons;